#!/usr/bin/env node
// Unit test for the managed ~/bin/claude launcher generated by install.mjs.
//
// We exercise the installer in a sandboxed HOME (no real Claude binary, so the
// patch step is skipped) and assert the three idempotent wrapper outcomes plus
// the runtime contract of the managed block:
//   - fresh: create a valid wrapper with markers + a flag-aware exec line
//   - marker-replace: refresh the block in place, preserving user env above it
//   - no-marker existing: back up the old file and regenerate
//   - runtime: resolve the NEWEST version (semver, not lexical) and exec it
//     directly with PATCHPRESS_CLAUDE_FLAGS + "$@"

import { mkdtempSync, writeFileSync, mkdirSync, readFileSync, existsSync, readdirSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const INSTALL = join(__dirname, "install.mjs");
const BEGIN = "# >>> patchpress managed block >>>";
const END = "# <<< patchpress managed block <<<";

function assert(cond, label) {
  if (!cond) throw new Error("FAIL: " + label);
}

function runInstall(home, extra = []) {
  return spawnSync(process.execPath, [INSTALL, ...extra], {
    env: { ...process.env, HOME: home },
    encoding: "utf8",
  });
}

function countOccurrences(s, sub) {
  return s.split(sub).length - 1;
}

let passed = 0;

// Test 1: fresh install creates a valid, marker-delimited wrapper.
{
  const home = mkdtempSync(join(tmpdir(), "pp-wrap-"));
  const r = runInstall(home);
  assert(r.status === 0, "installer exits 0 (no Claude binary present)");
  const wrapper = join(home, "bin", "claude");
  assert(existsSync(wrapper), "wrapper created at ~/bin/claude");
  const txt = readFileSync(wrapper, "utf8");
  assert(countOccurrences(txt, BEGIN) === 1, "exactly one BEGIN marker");
  assert(countOccurrences(txt, END) === 1, "exactly one END marker");
  assert(/exec "\$\{PATCHPRESS_CLAUDE_BIN:-\$HOME\/.local\/bin\/claude\}" \$\{PATCHPRESS_CLAUDE_FLAGS:-\} "\$@"/.test(txt), "flag-aware exec line present");
  const check = spawnSync("bash", ["-n", wrapper], { encoding: "utf8" });
  assert(check.status === 0, "generated wrapper is valid bash (bash -n): " + check.stderr);
  passed++;
  console.log("OK fresh install creates valid marker-delimited wrapper");
}

// Test 2: marker-replace preserves user env above the block; one block only.
{
  const home = mkdtempSync(join(tmpdir(), "pp-wrap-"));
  runInstall(home);
  const wrapper = join(home, "bin", "claude");
  const block = readFileSync(wrapper, "utf8").slice(readFileSync(wrapper, "utf8").indexOf(BEGIN));
  const userRegion = "#!/bin/bash\nset -euo pipefail\nexport MY_SENTINEL=1\nexport PATCHPRESS_CLAUDE_FLAGS=\"--dangerously-skip-permissions\"\n\n";
  writeFileSync(wrapper, userRegion + block);
  const r = runInstall(home);
  assert(r.status === 0, "installer exits 0 on re-run");
  const txt = readFileSync(wrapper, "utf8");
  assert(/export MY_SENTINEL=1/.test(txt), "user env preserved across re-install");
  assert(countOccurrences(txt, BEGIN) === 1, "still exactly one managed block after refresh");
  const check = spawnSync("bash", ["-n", wrapper], { encoding: "utf8" });
  assert(check.status === 0, "refreshed wrapper still valid bash");
  passed++;
  console.log("OK marker-replace preserves user env and keeps a single block");
}

// Test 3: existing wrapper without markers is backed up and regenerated.
{
  const home = mkdtempSync(join(tmpdir(), "pp-wrap-"));
  mkdirSync(join(home, "bin"), { recursive: true });
  const wrapper = join(home, "bin", "claude");
  writeFileSync(wrapper, "#!/bin/bash\necho old\nexec claude \"$@\"\n");
  const r = runInstall(home);
  assert(r.status === 0, "installer exits 0 on no-marker file");
  const baks = readdirSync(join(home, "bin")).filter((f) => f.startsWith("claude.bak-"));
  assert(baks.length === 1, "exactly one backup created");
  const txt = readFileSync(wrapper, "utf8");
  assert(txt.includes(BEGIN), "regenerated file has the managed block");
  passed++;
  console.log("OK no-marker wrapper is backed up and regenerated");
}

// Test 4: --no-wrapper leaves ~/bin/claude untouched.
{
  const home = mkdtempSync(join(tmpdir(), "pp-wrap-"));
  const r = runInstall(home, ["--no-wrapper"]);
  assert(r.status === 0, "installer exits 0 with --no-wrapper");
  assert(!existsSync(join(home, "bin", "claude")), "no wrapper written under --no-wrapper");
  passed++;
  console.log("OK --no-wrapper skips wrapper management");
}

// Test 5: runtime — the block resolves the NEWEST version (semver) and execs it.
{
  const home = mkdtempSync(join(tmpdir(), "pp-wrap-"));
  runInstall(home);
  const wrapper = join(home, "bin", "claude");
  const vd = join(home, "versions");
  mkdirSync(vd, { recursive: true });
  for (const v of ["2.1.180", "2.1.9", "2.1.187"]) {
    const p = join(vd, v);
    writeFileSync(p, `#!/bin/bash\necho "RAN $0 [$*]"\n`);
    chmodSync(p, 0o755);
  }
  // Short-circuit the patch path: stamp already matches, throttle window closed.
  const pps = join(home, ".local/share/patchpress");
  mkdirSync(pps, { recursive: true });
  writeFileSync(join(pps, ".patched"), "2.1.187 \n");
  writeFileSync(join(pps, ".lastcheck"), "");
  const run = spawnSync("bash", [wrapper, "hello", "x"], {
    env: { ...process.env, HOME: home, CLAUDE_VERSIONS_DIR: vd, PATCHPRESS_CHECK_TTL: "999999", PATCHPRESS_CLAUDE_FLAGS: "--demo" },
    encoding: "utf8",
  });
  assert(run.status === 0, "wrapper runtime exits 0");
  assert(/RAN .*\/versions\/2\.1\.187 \[--demo hello x\]/.test(run.stdout), "execs NEWEST version with flags + args: " + JSON.stringify(run.stdout));
  passed++;
  console.log("OK managed block resolves newest version and execs it with flags+args");
}

console.log(`\nwrapper test passed (${passed} assertion groups).`);
